services:
  traefik:
    image: "traefik:v3.1"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:8000"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: ./user_service
    environment:
      - DATABASE_URL=postgresql://user:password@user_db/users
      - SECRET_KEY=mysecretkey
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=Host(`127.0.0.1`) && PathPrefix(`/users`)"
      - "traefik.http.services.user-service.loadbalancer.server.port=8001"
    volumes:
      - ./user_service:/app
    depends_on:
      - user_db
      - rabbitmq
    networks:
      - traefik_network
        # entrypoint: ["/app/wait-for-it.sh", "user_db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  tracking-service:
    build:
      context: ./tracking_service
    environment:
      - DATABASE_URL=postgresql://user:password@tracking_db/trackings
      - SECRET_KEY=mysecretkey
      - USER_SERVICE_URL=http://user-service:8001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking-service.rule=Host(`127.0.0.1`) && PathPrefix(`/trackings`)"
      - "traefik.http.services.tracking-service.loadbalancer.server.port=8002"
    volumes:
      - ./tracking_service:/app
    depends_on:
      - tracking_db
      - rabbitmq
    networks:
      - traefik_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- ./wait-for-it.sh tracking_db:5432 -- uvicorn main:app --host 0.0.0.0 --port 8002 --reload"]

  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - traefik_network

  tracking_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trackings
    volumes:
      - tracking_db_data:/var/lib/postgresql/data
    networks:
      - traefik_network

volumes:
  user_db_data:
  tracking_db_data:

networks:
  traefik_network:
