[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
'''
[tool.pyright]
# Pyright-specific settings
typeCheckingMode = "normal"
reportMissingImports = "none"
reportUnusedVariable = "none"

[tool.pytest.ini_options]
markers = [
    "update: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E501"]
# W503 und W504 und B001 sind in ruff (noch) nicht implementiert (21.06.2024)
ignore = ["N806", "F402", "F405", "F403",  "C408", "C416", "T201", "SIM102"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 72

[tool.isort]
profile = "black"
line_length = 88
force_grid_wrap = 0
force_single_line = false
use_parentheses = true
ensure_newline_before_comments = true
include_trailing_comma = true
lines_after_imports = 2
multi_line_output = 3
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "DJANGO", "LOCALFOLDER"]
known_django = ["django"]
skip = ["migrations"]
skip_glob = ["docs/*", "setup.py",]

[tool.mypy]
follow_imports = "silent"
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
check_untyped_defs= false
disallow_subclassing_any = false
strict_optional = false
no_implicit_optional = false
disallow_incomplete_defs = true
disallow_untyped_defs = false
warn_no_return = false
warn_unreachable = true
